steps:
- name: gcr.io/cloud-builders/docker
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/godns:$COMMIT_SHA', 
    '-f',
    'Dockerfile',
    '.'
  ]
- name: gcr.io/cloud-builders/docker
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/godns-arm:$COMMIT_SHA', 
    '-f',
    'Dockerfile.arm',
    '.'
  ]
- name: gcr.io/cloud-builders/docker
  args: [
    'tag',
    'gcr.io/$PROJECT_ID/godns-arm:$COMMIT_SHA', 
    'gcr.io/$PROJECT_ID/godns-arm:latest'
  ]
- name: gcr.io/cloud-builders/docker
  args: [
    'tag',
    'gcr.io/$PROJECT_ID/godns:$COMMIT_SHA', 
    'gcr.io/$PROJECT_ID/godns:latest'
  ]
images: [
  'gcr.io/$PROJECT_ID/godns-arm:latest',
  'gcr.io/$PROJECT_ID/godns:latest',
  'gcr.io/$PROJECT_ID/godns-arm:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/godns:$COMMIT_SHA'
]