name: WIP
on:
  pull_request:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        args: --timeout 5m0s

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - run: go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
